[package]
name = "rust_project"
version = "0.1.0"
edition = "2021"
futures = "0.3.13"
nix = "0.20.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
